varnish/varnish-modules

src/Makefile.am

make distcheck first makes a distribution and then tries to do a VPATH build.
A complete path to where the *vcc files lie is necessary to install the package during the VPATH build.
Fixes #1

Provide absolute path for vcc files for extra_dist

---

src/tests/cookie/10-parser.vtc
src/vmod_cookie.c

sep != '\0' is always true (see if (sep == NULL) above).
If *sep == '\0', the parser will skip over the NUL terminator
and keep parsing other headers and the request body looking
for cookies.

Fix cookie parsing

---

configure.ac
src/vmod_tcp.c

Works on my machine, how about on @quintonparker's?

Fugly rules to omit vmod-tcp when unsupported

---

src/vmod_cookie.c
src/vmod_header.c
src/vmod_saintmode.c
src/vmod_softpurge.c
src/vmod_tcp.c
src/vmod_var.c
src/vmod_vsthrottle.c
src/vmod_xkey.c

- config.h first
- cache.h or (additional) vdef.h before vrt.h
this is required for master since 81bc4cef2a5e651a9e34ae5400672a88663db7ef
Survives make check with 5.0 release and 4.1 branch

cleanup include order

---

configure.ac

build on centos6 requires autoconf-2.65, automake-1.13, and this change
in configure.ac

fix build on centos6

---

docs/vmod_cookie.rst

As discussed with @gquintard in issue #66 this VMOD shouldn't be used to manipulate
the Set-Cookie response headers. This small change tries to make the documentation clearer.

Clearify documentation on vmod-cookie and Set-Cookie

---

README.rst

When @mhagander tried to build the modules on a box with the project packages, the instructions were wrong regarding packages to install for development deps.

Improve docs to work with both packagesets.

---

docs/vmod_xkey.rst

Adjusts docs for two things:
- That space separated values also work _(like in the original Surrogate-Key case)_
- Reflect that purge can take several values now _(since 0.10.2 in f723b4c25f292fcad85c9fac88e20d64e2d08ea0)_

[xkey doc] Add example for use with space separated headers

---

CHANGES.rst
src/Makefile.am
src/tests/saintmode/test04.vtc
src/tests/saintmode/test05.vtc
src/vmod_saintmode.c
src/vmod_saintmode.vcc

To issue "Saint mode : std.healthy return true even if backend is in blacklist." #27
new function to check obj (req/busyobj) health

Saintmode health

---

src/vmod_tcp.c

Since other VMODs in this package are already using VCL_INT, I switched
the function to use this type instead of doing any complex gating.
In the interests of keeping this file consistent, I switched to VRT_CTX
in all vmod_ methods in this file, as that's what other VMODs in this
repo use.
And thanks for the work already done to port this to Varnish 6. It's appreciated!

Fix vmod_tcp for Varnish 6 - VCL_INT changed type

---

src/Makefile.am
src/tests/xkey/test09.vtc
src/vmod_xkey.c

A possible fix for Issue #102
In this PR, I'm assuming that Varnish itself is handling folded header values for us.
One possible point where this may break from existing (invalid) assumptions is if an origin server is sending a surrogate key like "foo,bar", however RFC 2616 does suggest that this should be considered two separate headers having been combined into one.

Xkey: Allow comma between keys per RFC2616

---

src/Makefile.am
src/tests/cookie/34-vcl_discard.vtc
src/vmod_cookie.c

The PRIV_CALL regular expressions used to be leaked at vcl.discard time
and only the vre_t was freed.

Plug regex leak in vmod_cookie

---

src/Makefile.am
src/tests/xkey/test12.vtc
src/vmod_xkey.c
src/xkey.vsc

Adds gauges for bytes used by vmod_xkey's data structures
Co-Authored-By: Ben Zvan <ben.zvan@target.com>

Xkey bytes

---

docs/vmod_var.rst
src/vmod_var.vcc

The module supports durations, ip addresses and backends which was not
listed in the documentation header. Also clarify that global variables
are string only.

Update documentation of vmod_var variable types

---

src/tests/header/append.vtc
src/tests/header/get.vtc
src/vmod_header.c
src/vmod_header.vcc

See also #147 
This solves the following use cases:
* construction of header names at vcl runtime
* use of header names not supported by vcl syntax

add header.dyn to create dynamic headers

---

src/vmod_xkey.vcc

The documentation isn't in sync with the example VCL anymore. This PR fixes the issue. The problem has been introduced by f3529e1e36b70bb117ef7664ab9f6aaaa0e81987.

Fix xkey docs

---

src/tests/xkey/test12.vtc

ref varnish-cache e1ac59335f749b84280722425b355be344cc76e9
not sure if this is going to stay, but this change makes tests pass with current varnish-cache master

VRBT shrunk in size

---

src/vmod_header.c

This reverts 81231af3295e1464574cda4dfac238b548e08c19. I believe its not accepted practice to do dynamic stack allocations like this. In this case, there are no bounds checks and also, as with all stack allocations, no way to detect a stack overflow or failure (aside from getting a segfault).

Revert "Construct intermediate strands on the stack" commit

---

src/vmod_xkey.c

We end up using the wrong list, and therefore fails to cleanup properly (leaking
oc refs). Also add OBJ_CHECK_NOTNULL before FREE_OBJ to ensure that we free the
intended object.
Signed-off-by: Asad Sajjad Ahmed <asadsa@varnish-software.com>

xkey: plug xkey_cleanup memory leaks

---

README.md

installing the modules fails when the doc has not been built

clarify make install

---

src/Makefile.am
src/tests/var/test06.vtc
src/vmod_var.c

The assumption that `WS_Alloc` always returns a non-NULL value is not
true, which can lead to the `AN(v)` following the call to `WS_Alloc` in
`vmod_var` to kill the varnish child process, resulting in a loss of the
cache.
Instead of panicking due to a failed assertion, this commit introduces a
check of the return value of `WS_Alloc` and fails the request in case
not enough memory was available for allocating a new variable.

fix(vmod_var): gracefully handle WS_Alloc failures

---

src/Makefile.am
src/tests/vsthrottle/test05.vtc
src/vmod_vsthrottle.c
src/vmod_vsthrottle.vcc

VOID remove_bucket(STRING key, INT limit, DURATION period, DURATION block)
Arguments:
- Same arguments as is_denied()
Description
Remove the token bucket identified by the four parameters, if it exists.
Example:
sub vcl_deliver {
vsthrottle.remove_bucket(client.identity, 15, 10s, 30s);
}
it fixes the issue #204

Add vsthrottle.remove_bucket()

---

src/tests/saintmode/test06.vtc
src/vmod_saintmode.vcc

Removes archaic references to `blacklist` and replaces with more descriptive terms. Includes aliases, examples, and log messages.
method .blacklist --> .denylist
method .blacklist_count --> .denylist_count
TODO: saintmode.c still uses old code and terms.

Updates saintmode language and aliases

---

src/Makefile.am
src/tests/xkey/test14.vtc
src/vmod_xkey.c

We only use `ctx->now`.
Removing the asserts will allow users to call `xkey.purge()` from a backend context, if that's a too big of a footgun, we can use `$Restrict`

remove unnecessary asserts
